# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rufus-jig}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Mettraux", "Kenneth Kalmer"]
  s.date = %q{2010-11-30}
  s.description = %q{
    Json Interwebs Get.

    An HTTP client, greedy with JSON content, GETting conditionally.

    Uses Yajl-ruby whenever possible.
  }
  s.email = %q{jmettraux@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".rspec",
     "CHANGELOG.txt",
     "CREDITS.txt",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "TODO.txt",
     "lib/rufus-jig.rb",
     "lib/rufus/jig.rb",
     "lib/rufus/jig/adapters/em.rb",
     "lib/rufus/jig/adapters/net.rb",
     "lib/rufus/jig/adapters/net_persistent.rb",
     "lib/rufus/jig/adapters/net_response.rb",
     "lib/rufus/jig/adapters/patron.rb",
     "lib/rufus/jig/couch.rb",
     "lib/rufus/jig/http.rb",
     "lib/rufus/jig/path.rb",
     "lib/rufus/jig/version.rb",
     "rufus-jig.gemspec",
     "spec/couch/couch_attachements_spec.rb",
     "spec/couch/couch_continuous.rb",
     "spec/couch/couch_db_spec.rb",
     "spec/couch/couch_spec.rb",
     "spec/couch/couch_views_spec.rb",
     "spec/couch/tweet.png",
     "spec/couch_url.txt",
     "spec/spec_helper.rb",
     "spec/support/couch_helper.rb",
     "test/base.rb",
     "test/bm/bm0.rb",
     "test/bm/bm1.rb",
     "test/conc/put_vs_delete.rb",
     "test/couch_base.rb",
     "test/couch_url.txt",
     "test/cut_0_auth_couch.rb",
     "test/server.rb",
     "test/test.rb",
     "test/to.sh",
     "test/tt_0_get_timeout.rb",
     "test/tweet.png",
     "test/ut_0_http_get.rb",
     "test/ut_1_http_post.rb",
     "test/ut_2_http_delete.rb",
     "test/ut_3_http_put.rb",
     "test/ut_4_http_prefix.rb",
     "test/ut_5_http_misc.rb",
     "test/ut_6_args.rb",
     "test/ut_7_parse_uri.rb",
     "test/ut_8_auth.rb"
  ]
  s.homepage = %q{http://github.com/jmettraux/rufus-jig/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rufus}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An HTTP client, greedy with JSON content, GETting conditionally.}
  s.test_files = [
    "spec/couch/couch_attachements_spec.rb",
     "spec/couch/couch_continuous.rb",
     "spec/couch/couch_db_spec.rb",
     "spec/couch/couch_spec.rb",
     "spec/couch/couch_views_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/couch_helper.rb",
     "test/base.rb",
     "test/bm/bm0.rb",
     "test/bm/bm1.rb",
     "test/conc/put_vs_delete.rb",
     "test/couch_base.rb",
     "test/cut_0_auth_couch.rb",
     "test/server.rb",
     "test/test.rb",
     "test/tt_0_get_timeout.rb",
     "test/ut_0_http_get.rb",
     "test/ut_1_http_post.rb",
     "test/ut_2_http_delete.rb",
     "test/ut_3_http_put.rb",
     "test/ut_4_http_prefix.rb",
     "test/ut_5_http_misc.rb",
     "test/ut_6_args.rb",
     "test/ut_7_parse_uri.rb",
     "test/ut_8_auth.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rufus-lru>, [">= 0"])
      s.add_runtime_dependency(%q<rufus-json>, [">= 0.2.5"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.2.0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<patron>, [">= 0"])
      s.add_development_dependency(%q<em-http-request>, [">= 0"])
      s.add_development_dependency(%q<net-http-persistent>, [">= 1.4"])
    else
      s.add_dependency(%q<rufus-lru>, [">= 0"])
      s.add_dependency(%q<rufus-json>, [">= 0.2.5"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.2.0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<patron>, [">= 0"])
      s.add_dependency(%q<em-http-request>, [">= 0"])
      s.add_dependency(%q<net-http-persistent>, [">= 1.4"])
    end
  else
    s.add_dependency(%q<rufus-lru>, [">= 0"])
    s.add_dependency(%q<rufus-json>, [">= 0.2.5"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.2.0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<patron>, [">= 0"])
    s.add_dependency(%q<em-http-request>, [">= 0"])
    s.add_dependency(%q<net-http-persistent>, [">= 1.4"])
  end
end

